### DISCUSSION TITLE
Status Update: 2022-04-13

### DISCUSSION THREAD

**Discussion by phil-opp** [dora-rs/dora#22] [Status Update]
In this discussion, we describe our recent progress and the main topics that we would like to discuss in today's meeting. We use a separate post for each topic to keep the discussion focused. Feel free to create new posts for topics that are not mentioned yet.

**Comment by phil-opp** [comment]
## Design Overview

Our current design draft looks like this:

![library-based-dora-design drawio](https://user-images.githubusercontent.com/1131315/163211975-7616a9e7-debf-43a1-984f-27502b1ff3ed.svg)

The coordinator is responsible for reading the dataflow from a YAML file, verifying it, and deploying the operators to the specified or automatically determined machines. It monitors the operator's health and implements high level cluster management functionality. For example, we could implement automatic scaling for cloud nodes or operator replication and restarts. The coordinator can be controlled through a command line program (CLI).

Dora provides its main functionality through an API, ideally for multiple languages. Operators communicate through a shared communication layer, which will be zenoh in the first iteration. However, we will design dora in a way that makes it easy to use different communication layers in the future. All communication layers should be robust against disconnections, so operators should be able to keep running even if they lose the connection to the coordinator.

## Light-weight and Heavy-weight Operators

Dora supports two types of operators: _heavy-weight_ and _light-weight_ operators. _(The names are only placeholders for now.)_

Each heavy-weight operator is a separate, isolated process that communicates with other operators through the dora library. This operator type is for example useful for security-critical operators (isolation is important), resource-heavy operators (resources can be pinned to processes), or operators which need maximal control (e.g. for complex input rules). However, running each operator has a separate executable also has some drawbacks. For example, the isolation between operators comes with some overhead and not all features of dora are usable (e.g. no real-time support). For this reason, dora also supports so-called _light-weight_ operators, organized into operators groups.

Light-weight operators are cooperative, library-based components that are executed by a dora runtime process. Multiple formats are supported for light-weight operators, for example they can be implemented as a Python object, a WebAssembly module, or a traditional C-compatible shared library. The dora runtime links multiple light-weight operators (of the same operator group) together and executes them from a single, multi-threaded process. The full set of dora's features are available for light-weight operators, for example priority scheduling or native deadline support.

**Reply by heyong4725** [reply]
I think we can unify all long running processes/daemons, which include: dora-rs runtime (for light-weight operators), heavy-weight operators, control plane processes (e.g. YAML processor, cluster management, monitoring etc). In future, all of these daemons can be packaged into containers and managed by cloud native K8S.

**Reply by phil-opp** [reply]
I updated the design docs: https://github.com/futurewei-tech/dora-rs/blob/main/design/overview.md

We now use the term "node" instead of "heavy-weight operator" and "operator" instead of "light-weight operator". I also updated the design diagram to include dora operators and the corresponding runtime node, and rewrote the text to include more details.

**Reply by haixuanTao** [reply]
Thanks! I feel like for WASM and Python, executing them in a custom node or a Dora Runtime Node is not going to make that much of a difference. (in term of efficiency, excluding IO)
I feel that custom nodes are more geared toward Rust-written nodes or C-written nodes. 

What do you think?

**Reply by phil-opp** [reply]
Agreed! I pushed https://github.com/futurewei-tech/dora-rs/commit/2bfdd68024ae2bf389957beca2cc1981d23ae2e4 to list them only as "maybe".

**Comment by phil-opp** [comment]
## Dataflow Specification

Dataflows are specified through a YAML file. This section presents our current draft for the file format. It only includes basic functionality for now, we will extend it later when we introduce more advanced features.

### Run Operation

For heavy-weight operators (see https://github.com/futurewei-tech/dora-rs/discussions/22#discussioncomment-2560618), we plan to specify the executable name and arguments like a normal shell operation:

```yaml
operators:
  - run: path/to/executable arg1 arg2
    env:
      - ENVIRONMENT_VARIABLE_1: true
    working-directory: some/path
    inputs: # ...
    outputs: # ...
````

This way, we stay close to popular continuous integration (CI) services such as GitHub Actions, so the format should already be familiar to many people. We haven't decided yet on a syntax for light-weight operators.

### Dataflow Graph


Each operator has a separate namespace for its outputs. To refer to outputs, the `<operator>/<output>` syntax is used. This way, there are no name conflicts between operators.

Input operands are specified using the `<name>: <operator>/<output>` syntax, where `<data>` is the internal name that should be used for the operand. The main advantage of this name mapping is that the same operator executable can be reused multiple times on different input.

#### Example

```yaml
operators:
  # sources (only outputs)
  - id: timer
    name: Clock timer    # optional, human-readable name
    description: Send the time.
    run: path/to/timer --interval 0.5
    outputs:
      - time
  - id: camera-uuid-1
    name: Front camera
    run: camera --id camera_id
    outputs:
      - image
      - metadata
  - id: camera-uuid-2
    name: Front camera
    run: camera --id camera_id
    outputs:
      - image
      - metadata
      
  # actions (inputs and outputs)
  - id: timestamp
    description: Add a watermark on the camera.
    run: path/to/timestamp
    inputs:
      timestamp: timer/time
      image: camera-uuid-1/image
    outputs:
      - image # with timestamp watermark

  # sinks (only inputs)
  - id: logger
    description: Sink the data into the logger.
    run: path/to/logger --target-dir /foo/bar
    inputs:
      image: timestamp/image
      camera: camera-uuid-2/metadata
```
    
#### Visualized

```mermaid
flowchart TB
  timer[\timer/]
  camera[\camera/]
  timestamp
  logger[/logger\]
  camera -- image as pic --> timestamp
  timer -- time as timestamp --> timestamp
  timestamp -- image as data --> logger
  timer -- time --> logger
```

### Integration with ROS 1/2

To integrate dora-rs operators with ROS1 or ROS2 operators, we plan to provide special _bridge operators_. These operators act as a sink in one dataflow framework and push all messages to a different dataflow framework, where they act as source.

For example, we plan to provide a `to_ros_2` operator, which takes a single `data` input, which is then published to a specified ROS 2 dataflow.
