### DISCUSSION TITLE
Status Update: 2022-04-27

### DISCUSSION THREAD

**Discussion by haixuanTao** [dora-rs/dora#23] [Status Update]
In this discussion, we describe our recent progress and the main topics that we would like to discuss in today's meeting. We use a separate post for each topic to keep the discussion focused. Feel free to create new posts for topics that are not mentioned yet.

**Comment by haixuanTao** [comment]
## Design Changes

We decided on a new naming convention for light-weight and heavy-weight operators. We also updated our design diagram and the dataflow configuration format to include both operator types.

### New Names

- **_operator_** instead of _light-weight operator_
- **_node_** instead of _heavy-weight operator_
    - _dora runtime nodes_ execute operators
    - _custom nodes_ are user-provided executables

In our design documentation, we describe the differences between operators and custom nodes in the following way:

> Operators have the following advantages:
>
> - They can use a wide range of advanced functionality provided by the dora runtime nodes. This includes special scheduling strategies and features such as deadlines. 
> - They are _light-weight_, so they only occupy minimal amounts of memory. This makes it possible to run thousands of operators on the same machine.
> - They can use runtime-managed state storage, for robustness or for sharing state with other operators.
> - They _share the address space_ with other operators on the same node, which makes communication much faster.
>
> Custom nodes provide a different set of advantages:
>
> - Each node is a separate, isolated process, which can be important for security-critical operations.
> - They support pinned resources. For example, a CPU core can be pinned to a custom node through the dataflow configuration file.
> - They have full control over their execution, which allows to create complex input and wake-up rules.

#### Special Handling for Python Operators

Since Python still uses a global interpreter lock, which effectively limits the possible concurrency across threads, we need some special handling for operators written in Python. Instead of running multiple Python operators on the same node, we spawn a separate runtime subprocess for them. The runtime subprocesses communicate with the parent process via shared memory, so the overhead should be negligible.

### Updated Design Diagram

![](https://github.com/futurewei-tech/dora-rs/raw/main/design/overview.svg)

### Changes to Dataflow Config Format

We updated the YAML format for specifying nodes and operators.

**Nodes:**

```yaml
- id: some-unique-id
  name: Human-Readable Node Name
  description: An optional description of the node's purpose.

  # EITHER:
  operators:
    - id: operator-1
      # ... (see below)
    - id: operator-2
      # ... (see below)

  # OR:
  custom:    
    run: path/to/timestamp
    env:
      - ENVIRONMENT_VARIABLE_1: true
    working-directory: some/path

    inputs:
      input_1: operator_2/output_4
      input_2: custom_node_2/output_4
    outputs:
      - output_1
```

**Operators:**

```yaml
- id: unique-operator-id
  name: Human-Readable Operator Name
  description: An optional description of the operators's purpose.

  inputs:
    input_1: source_operator_2/output_1
    input_2: custom_node_1/output_1
  outputs:
    - output_1
  
  ## ONE OF:
  shared_library: "path/to/shared_lib.so"
  python: "path/to/python_file.py"
  wasm: "path/to/wasm_file.wasm"
```

### New Visualization

We updated our dataflow visualization code to take runtime nodes and operators into account:

```mermaid
flowchart TB
  timer[\timer/]
  camera[\camera/]
subgraph node-1[__node1]
  node-1/operator-1[operator-1]
  node-1/operator-2[operator-2]
end
  printer[/printer\]
  camera -- image --> node-1/operator-1
  node-1/operator-1 -- processed --> node-1/operator-2
  timer -- time --> node-1/operator-2
  node-1/operator-2 -- processed --> printer
  timer -- time --> printer
```
