### DISCUSSION TITLE
Python node API

### DISCUSSION THREAD

**Discussion by haixuanTao** [dora-rs/dora#49] [Done]
## Python Node proposal

- yaml API example:

```yaml
  - id: control_node
    custom:
      outputs:
        - control_status
      inputs:
        control: pid_control_node/control
        vehicle_id: carla_source_node/vehicle_id
      run: python control_node.py
```

### Dora node Python

After discussing with Philipp, we agreed on implementing a "oneshot" Python node function that reflects the Rust Node API. The idea is to let full control of the user. 

```python
from dora import Session

session = Session()

session.next() # DoraInput

# ...

session.send_output("channel", data)
```
