### DISCUSSION TITLE
Is there a quick way to close multiple Dora nodes？

### DISCUSSION THREAD

**Discussion by Ryu-Yang** [dora-rs/dora#738] [Q&A] [answered]
I’m writing for the driver node of the depth camera `Orbbec Gemini 355`. I created a dora-orbbec node to get the image and depth data, and show them in a view node.

I need to detect key presses inside the code, and when the ESC key is detected, execute some code and close the Dora node.

I use `cv2.waitKey()` in the view node. When I press the `ESC` button, it will break the for loop and close the cv2 window, and then this node will end. However, the dora-orbbec node does not terminate along with the view node.

The dataflow and code is as follows.

test.yml

```
nodes:
  - id: dora-orbbec
    path: dora_orbbec.py
    inputs:
      tick: dora/timer/millis/30
    outputs:
      - rgb
      - depth

  - id: view
    path: view.py
    inputs:
      rgb:
        source: dora-orbbec/rgb
        queue_size: 1
      depth:
        source: dora-orbbec/depth
        queue_size: 1

```

dora_orbbec.py

```python

...  # import and class define

node = Node()
config = Config()
pipeline = Pipeline()

...  # init camera

pipeline.start(config)

for event in node:
    if event["type"] == "INPUT":
        frames = pipeline.wait_for_frames(20)
        if frames is None:
            continue

        ...  # Get Depth data
        storage = pa.array(depth_data.ravel())
        node.send_output("depth", storage)

        ...  # Get Color image
        storage = pa.array(color_image.ravel())
        node.send_output("rgb", storage)

pipeline.stop()  # I need to execute this line before ending this dora node

```

view.py

```python
from dora import Node
import cv2
import numpy as np


node = Node()

for event in node:
    if event["type"] == "INPUT":
        if event["id"] == "rgb":
            data = event["value"].to_numpy()
            color_image = data.reshape((480, 640, 3)).astype(np.uint8)
            cv2.imshow("Color Viewer", color_image)
            print(color_image)

        if event["id"] == "depth":
            data = event["value"].to_numpy()
            depth_data = data.astype(np.uint16).reshape((480, 640))

            depth_image = cv2.normalize(depth_data, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
            depth_image = cv2.applyColorMap(depth_image, cv2.COLORMAP_JET)

            cv2.imshow("Depth Viewer", depth_image)
            print(depth_data)

        key = cv2.waitKey(1)
        if key == ord('q') or key == 27:  # I need to end all dora nodes after pressing the button
            break

cv2.destroyAllWindows()  # I need to execute this line before ending this dora node

```

When I pressed the ESC button, Dora only exited the view node：

![image](https://github.com/user-attachments/assets/b758ef0d-14c1-4188-87a3-e54af080da3a)

I have tried to add a stop dataflow to make the dora-orbbec node close after the view node ends.

test.yml

```
nodes:
  - id: dora-orbbec
    path: dora_orbbec.py
    inputs:
      tick: dora/timer/millis/30
      stop: view/stop
    outputs:
      - rgb
      - depth

  - id: view
    path: view.py
    inputs:
      rgb:
        source: dora-orbbec/rgb
        queue_size: 1
      depth:
        source: dora-orbbec/depth
        queue_size: 1
    outputs:
      - stop
```

dora_orbbec.py

```python

...  # import and class define

node = Node()
config = Config()
pipeline = Pipeline()

...  # init camera

pipeline.start(config)

for event in node:
    if event["type"] == "INPUT":
        frames = pipeline.wait_for_frames(20)
        if frames is None:
            continue

        ...  # Get Depth data
        storage = pa.array(depth_data.ravel())
        node.send_output("depth", storage)

        ...  # Get Color image
        storage = pa.array(color_image.ravel())
        node.send_output("rgb", storage)

       if event["id"] == "stop":
           break

pipeline.stop()  # I need to execute this line before ending this dora node
```

view.py

```python
from dora import Node
import cv2
import numpy as np


node = Node()

for event in node:
    if event["type"] == "INPUT":
        if event["id"] == "rgb":
            data = event["value"].to_numpy()
            color_image = data.reshape((480, 640, 3)).astype(np.uint8)
            cv2.imshow("Color Viewer", color_image)
            print(color_image)

        if event["id"] == "depth":
            data = event["value"].to_numpy()
            depth_data = data.astype(np.uint16).reshape((480, 640))

            depth_image = cv2.normalize(depth_data, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
            depth_image = cv2.applyColorMap(depth_image, cv2.COLORMAP_JET)

            cv2.imshow("Depth Viewer", depth_image)
            print(depth_data)

        key = cv2.waitKey(1)
        if key == ord('q') or key == 27:  # I need to end all dora nodes after pressing the button
            node.send_output("stop", pa.array([0]))
            break

cv2.destroyAllWindows()  # I need to execute this line before ending this dora node
```

When I pressed the ESC button, Dora will exited the view node and dora-orbbec node, but it will take about 10 seconds ：
![image](https://github.com/user-attachments/assets/bac24454-97c6-4ed4-947c-35f80dd8eb51)
