### ISSUE TITLE
Dora-daemon and dora-coordinator are background process that does not see cli environment variable

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#363]
**Describe the bug**
Sometimes an environment variable is updated before using the dora-cli. But because the coordinator and the daemon are background process. They do not see the updated environment variable. This can generate some confusion.

**To Reproduce**
1. Dora start daemon: `dora up` 
2. **Change an env variable** 
3. Start a new dataflow: `dora start dataflow.yaml`
3. bis. Expect the env variable to be the latest one but see the previous one or an empty one
5. Stop dataflow: `dora stop`
6. Destroy dataflow: `dora destroy`

**Expected behavior**
I would expect the cli to pass the latest value to the daemon and coordinator.

**Comment by phil-opp** [comment]
> I would expect the cli to pass the latest value to the daemon and coordinator.

We need to keep deployment to remote machines in mind. We probably don't want the CLI to pass the local env variables to the remote deploy machine.

**Comment by phil-opp** [comment]
We already support setting environment variables through the dataflow yaml file, right? Would this be a possible alternative for your use case?

**Comment by haixuanTao** [comment]
So this is the thing, when we use environment variable within the YAML Graph,  it uses old env variables. 

In the case we think that environment variables should not be shared in a distributed environment which I can understand, maybe we should change our approach to using variables.

**Comment by haixuanTao** [comment]
One alternative would be to add a `--env` argument that enables user to pass env variable when running dataflows, in the manner of docker

**Comment by Hennzau** [comment]
Hi! I believe this issue is quite important when it comes to using Dora, especially for less experienced users. We expect that for the following dataflow:

```YAML
nodes:
  - id: camera
    path: camera.py
```

the `camera.py` file should be executed by the Python interpreter from the current CLI's `venv`. However, we understand that sharing the CLI's PATH with the Daemon might cause too many issues. So, why not add a new `activate` parameter to the dataflow? This parameter could always point to a script that extends a PATH, like so:

```YAML
nodes:
  - id: camera
    activate: .venv/bin/activate
    path: camera.py # this way `camera.py` will be resolved and launched by the `python` bin wanted by the user
```

We could also consider a configuration where the entire dataflow shares the same Python environment, like this:

```YAML
config:
    activate: .venv/bin/activate
nodes:
  - id: camera
    path: camera.py # this way `camera.py` will be resolved and launched by the `python` bin wanted by the user
```

In the case of a `distributed` dataflow, an absolute path would need to be specified, as with other elements.

**Comment by Hennzau** [comment]
### 🚀 Proposal: Enhancing Dora for Better Usability

Hello! I believe this unresolved issue is crucial for the better adoption of Dora, especially among less experienced users. At first glance, one might expect that our nodes and the Daemon would have access to the CLI's environment variables. However, it's completely understandable that this could lead to a lot of issues. I think there's a way to find an alternative solution.

### 🛠️ Current `build` Process

We already have a `build` process that can be assigned to nodes, which activates when we run `dora build`. This procedure is particularly useful when we need to install requirements or compile a program as it's usually slow.

### 💡 New Proposal: `preprocess` Procedure

It could be interesting to introduce another procedure called `preprocess`, which would contain a list of scripts to execute when running `dora start`, before trying to resolve and launch nodes. This would help enhance the environment of our dataflow or specific nodes. For example:

```YAML
preprocess:
  - id: activate_python
    path: .venv/bin/activate.sh  # Will activate a Python environment
  - id: load_env_var_ext
    path: .my_env_var.sh  # Will export useful custom environment variables

nodes:
  - id: camera
    path: camera.py # will be launched by the python env, regarding where was spawned the daemon and the CLI

  - id: plot
    path: plot.py # same
```

### 🔄 Node-Specific Environment Variables

If we need different environment variables for a particular node, we could add them like this:

```YAML
preprocess:
  - id: activate_python
    path: .venv/bin/activate.sh
  - id: load_env_var_ext
    path: .my_env_var.sh

nodes:
  - id: camera
    path: camera.py

  - id: plot
    path: plot.py

  - id: weird_script
    preprocess:
      - id: activate_another_python
        path: .another_venv/bin/activate.sh
    path: weird_script.py # will be launched by this other_python
```

### 🌐 Distributed Dataflow Consideration

In the case of a distributed dataflow, absolute paths will need to be specified instead of relative ones, just like with everything else.

Let me know what you think! 😊

**Comment by haixuanTao** [comment]
So I definitely feel there is something to be done with running command  before running the full nodes. 

I think the preprocess idea is really interesting!

I would maybe do couple of changes.

Maybe what we could do is be slightly more `github action like` and make it possible to have multiline shell script in the likes of:

```yaml
```

**Comment by Hennzau** [comment]
I'm okay with using multi-line commands inside the `run` parameter since filling both the `path` and `args` parameters may not be easy :)

**Comment by haixuanTao** [comment]
In all honesty, I'm drawn with using `run` as well as it is closer to github action, but I think that it makes it harder to maintain as it means adding another `key`, and knowing that this will not be backward compatible. Also, there might be errors in having both path and run set.

**Comment by haixuanTao** [comment]
I think one of the issue is that if we only have run, we don't really have a way to control the environment in which the shell itself is spawned with. Like is it using bash or zsh or powershell or cmd, ...

Those things we could manage with ( something like):

```yaml
      - id: terminal-print
        build: cargo build -p terminal-print
        path: /bin/zsh
        args: |
          source /opt/ros/humble/setup.bash 
          cargo run --example cxx-ros2-dataflow --features="ros2-examples"
```

**Comment by heyong4725** [comment]
Closing as fixed by architecture change, verified by live repro on current main.

## Verification

Performed the 2023 repro on `target/debug/dora` from `0919d0b9..` (today main):

```bash
# Daemon spawned with stale FOO
FOO=before dora up

# CLI invoked with fresh FOO (different from daemon)
FOO=after dora start dataflow.yml --attach
```

`dataflow.yml`:
```yaml
nodes:
  - id: printer
    path: /usr/bin/env
    env:
      FOO: $FOO
```

Output from the spawned node (`/usr/bin/env` prints all its env vars):
```
stdout  printer:  FOO=after
```

The node received `FOO=after` — the CLI process env value, **not** the daemon process env value. The 2023 staleness bug is gone.

## Why it works

Env-var expansion in dataflow YAML happens at **serde deserialization time in the CLI process**, not at spawn time in the daemon:

- `libraries/message/src/descriptor.rs:1128-1135` — `EnvValue` fields annotated `#[serde(deserialize_with = "with_expand_envs")]`.
- `with_expand_envs` is from the `serde-with-expand-env` crate, declared in `libraries/core/Cargo.toml:28` and `libraries/message/Cargo.toml:27`. It resolves `$VAR` against `std::env::var(...)` of the *process doing the deserialization*.
- `binaries/cli/src/command/start/mod.rs:119` calls `Descriptor::blocking_read(path)`, which goes through `serde_yaml::from_slice` in the CLI process. The descriptor sent to coordinator + daemon is already expanded — concrete string values, no `$VAR` references left for the daemon to (mis-)expand.

The daemons separate `shellexpand` call at `binaries/daemon/src/spawn/command.rs:55` only applies to the `path:` field and is locked to an allowlist (`HOME`, `USER`, `DORA_WORKSPACE`, `CARGO_MANIFEST_DIR`, `PWD`). None of those would meaningfully drift between consecutive `dora start` invocations.

## What was fixed instead of A/B/C/D

The 2023 thread proposed four fix approaches (A `--env` flag, B multi-line `run:`, C implicit propagation, D documented workaround). None of them got implemented. The actual fix is closest to **C in spirit** — env vars are propagated implicitly from the CLI — but at **YAML-parse time** (deserialize), not at start time. The `path:` field tightened to an allowlist is a security hardening on top, likely from an audit pass, that has the side effect of restricting which env vars matter on the daemon side at all.

## Net effect

- Original repro from the OP no longer reproduces.
- Live test on current main confirms.
- No further action needed; closing.
