### ISSUE TITLE
error in get webcame data

### ISSUE THREAD

**Issue by RuPingCen** [dora-rs/dora#379]
Hi, haixuanTao. i encountered a problem when i tried to follow the tutorial in the webcam_plot.
https://dora.carsmos.ai/docs/guides/getting-started/webcam_plot

here is the Dora command:
**_dora start dataflow_webcam.yml --attach --hot-reload --name webcam_**

and the terminator return the error messages:
```

3f45130a-a522-48c6-a89e-822dfa18d840
dataflow failed: errors occurred in dataflow 3f45130a-a522-48c6-a89e-822dfa18d840:
- machine ``:
    some nodes failed:
      - plot: 
        3f45130a-a522-48c6-a89e-822dfa18d840/plot failed with exit code 1.
    
        Check logs using: dora logs 3f45130a-a522-48c6-a89e-822dfa18d840 plot
                                
      - web_cam: 
        3f45130a-a522-48c6-a89e-822dfa18d840/web_cam failed with exit code 1.
    
        Check logs using: dora logs 3f45130a-a522-48c6-a89e-822dfa18d840 web_cam
                                
    Location:
        /home/runner/work/dora/dora/binaries/coordinator/src/listener.rs:91:56
```

the **dataflow_webcam.yml** file is :
```

nodes:
  - id: web_cam
    operator:
      python: op_webcam/webcam.py
      inputs:
        tick: dora/timer/millis/100
      outputs:
        - image
  - id: plot
    operator:
      python: op_webcam/plot.py
      inputs:
        image: web_cam/image
```
  

I confused about the error because when I use the python code to show the camera is ok,here is the python code:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import cv2
capture = cv2.VideoCapture(0)
while(True):
    ret, frame = capture.read()
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break 
```
