### ISSUE TITLE
2 Python Operators will share the same GIL

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#38]
By trying the following dataflow:
```yaml
communication:
  zenoh:
    prefix: /foo

nodes:
  - id: timer
    custom:
      run: ../target/release/examples/example_source_timer
      outputs:
        - time

  - id: rate-limited-timer
    custom:
      run: ../target/release/examples/rate_limit --seconds 0.5
      inputs:
        data: timer/time
      outputs:
        - rate_limited

  - id: random
    custom:
      run: ../target/release/examples/random_number
      inputs:
        timestamp: rate-limited-timer/rate_limited
      outputs:
        - number

  - id: logger
    custom:
      run: ../target/release/examples/example_sink_logger
      inputs:
        random: random/number
        time: timer/time
        timestamped-random: runtime-node/op-1/timestamped-random
       # c-counter: runtime-node/op-2/counter
        python-counter: runtime-node/op-4/counter

  - id: runtime-node
    operators:
      - id: op-1
        shared-library: ../target/release/libexample_operator.so
        inputs:
          random: random/number
          time: timer/time
        outputs:
          - timestamped-random
      # - id: op-2
        # shared-library: ../runtime/examples/c-operator/operator.so
        # inputs:
          # time: timer/time
        # outputs:
          # - counter
      - id: op-3
        python: ../runtime/examples/python-operator/op.py
        inputs:
          time-python: timer/time
        outputs:
          - counter
      - id: op-4
        python: ../runtime/examples/python-operator/op.py
        inputs:
          counter: runtime-node/op-3/counter
        outputs:
          - counter
```
with the recommended command:
```bash
cargo run --release -- run examples/mini-dataflow.yml
```
I am able to lock one of the two operator in a way that the queue of the operator never get unfilled.

I think we have to look at how to enable multithreading for `pyo3`.

I will investigate
