### ISSUE TITLE
dora python example error 

### ISSUE THREAD

**Issue by RuPingCen** [dora-rs/dora#407]
**Describe the bug**
We hope to display Dora node data by using ROS2 nodes, so we are trying [Python-ROS2-dataflow](https://github.com/dora-rs/dora/tree/main/examples/python-ros2-dataflow). When we use
```
ros2 run turtlesim turtlesim_node 
```
to launch turtlesim node, and another terminator input the command as follow:
```
dora up
dora start dataflow.yml --name test
```
The screen shows the turtle, but the dora node reports an error：

![image](https://github.com/dora-rs/dora/assets/18321455/ae76b2b7-d0f7-46bb-a17e-6a893531915c)

The dataflow.yml file
```
nodes:
  - id: turtle
    custom:
      source: ./random_turtle.py
      inputs:
        direction: control/direction
      outputs:
        - turtle_pose

  - id: control
    custom:
      source: ./control_node.py
      inputs:
        turtle_pose: turtle/turtle_pose
        tick: dora/timer/millis/500
      outputs:
        - direction
```

Can you give me some ideas on how to solve this error？
