### ISSUE TITLE
Error when a node receives two data streams

### ISSUE THREAD

**Issue by RuPingCen** [dora-rs/dora#502]
We try to use node C to receive data streams sent by two different nodes A and B. **Sometimes** the receiving node C will have the error shown in the figure below,

**[c node] received unexpected event: 2**

[
![1](https://github.com/dora-rs/dora/assets/18321455/ddfc6bba-2365-4f1d-894b-d9aa4eee6d2a)
](url)

This results in the functions on lines 126 and 130 of the code never being called, as shown in the figure below

 
![2](https://github.com/dora-rs/dora/assets/18321455/7ce58ac1-e7d6-4b5f-8751-967826950860)

Here is the dataflow.yaml

```
- id: controltest
    custom:
      source: controldata
      inputs:
        tick: dora/timer/millis/100
      outputs:
        - road_lane
      
  - id: road_lane
    custom:
      source: ../../map/road_line_publisher/build/road_lane_publisher_node
      inputs:
              DoraGnssPose: gnss_poser_sub/DoraGnssPose
              road_lane: controltest/road_lane
      outputs:
            - cur_pose_all
            
  - id: planning
    custom:
      source: ../../planning/routing_planning/build/routing_planning_node
      inputs:
              cur_pose_all: road_lane/cur_pose_all
              road_lane: controltest/road_lane
      outputs:
            - raw_path
```
