### ISSUE TITLE
 dora node packet loss

### ISSUE THREAD

**Issue by RuPingCen** [dora-rs/dora#515]
Describe the bug
The dora is V0.3.2.

I use two nodes. Node A is written in Python. Node B is written in c/c++.

Node A reads GPS data at a 20ms cycle and sends the data via a json string. Node B performs coordinate conversion by receiving data from node A, but I found that node B will lose data packets when receiving data from node A.

Here I print the seq number of the data pub by node A, the message count received by node B, and the time when the message was received. There was no packet loss at the beginning, but after running for a while, the message count received by node B was not equal to the seq value of the message.

And, the period of node B to receive data should normally be 20ms, which depends on the period of node A sending data. However, the following picture shows that the time difference between the two events is 40ms. （lower left corner）

here is the test code:
https://github.com/dora-rs/autoware.universe/blob/feature/autoware_dora/localization/ekf_localizer/test_ekf_dataflow.yml

![数据丢包](https://github.com/dora-rs/dora/assets/18321455/9584dfc7-e8e0-4637-a8eb-93f5cdbf1517)

**Comment by haixuanTao** [comment]
Could you try removing the sleep here: https://github.com/dora-rs/autoware.universe/blob/db29af5314dbe4c3c9c5c79ab78e33f2a8bbd327/localization/ekf_localizer/src/gnss_ekf.cc#L65

**Comment by RuPingCen** [comment]
The **_“EKF_fusion_pthread“”_** thread is the sleep of the thread that sends data and has nothing to do with data reception. Data packet loss has occurred when receiving data from other nodes in the function **“int run(void *dora_context) ”**.

**Comment by phil-opp** [comment]
Dora uses a default queue size of 10 for each input. If the receiver cannot keep up with the sender, dora deliberately drops some inputs (oldest first). If you set the `RUST_LOG` environment variable to `debug` you will see a "dropped X inputs because event queue was too full" in the command-line output.

You can set a custom queue size in your YAML file, e.g.: https://github.com/dora-rs/dora/blob/ea47a556a77f6c64f29ab07939d747edc8573671/examples/python-dataflow/dataflow.yml#L5-L8

**Comment by RuPingCen** [comment]
As you said I set the parameter queue_size: 100, but data packet loss still exists.

I check the logs for the python node "gnss" , which is normal pub the data with 4643.
![2024-05-29 10-25-16 的屏幕截图](https://github.com/dora-rs/dora/assets/18321455/bc9ba83d-8fa2-4179-bcca-9977b6bca4f0)

The second node  **"gnss_poser"** with c/c++ finally received only 4229 data_seq.

![2024-05-29 10-22-17 的屏幕截图](https://github.com/dora-rs/dora/assets/18321455/6442da33-0040-4ebd-bcf9-6ac83ad566fa)

This phenomenon started to occur when receiving the 33rd data seq.
![2024-05-29 10-23-10 的屏幕截图](https://github.com/dora-rs/dora/assets/18321455/f771822b-2a5e-4ce5-909e-4af125e3c831)

here is the xxx.yaml file:
```
nodes:
  - id: gnss
    operator:
      python: ../../dora-hardware/vendors/gnss/CGI_610/CGI_610_driver_dora_with_file.py  #读取文件用于测试
      #python: ../../dora-hardware/vendors/gnss/CGI_610/CGI_610_driver_dora.py
      inputs:
        tick: dora/timer/millis/20
      outputs:
        - DoraSentence
        - DoraNavSatFix
        - DoraQuaternionStamped
        - DoraTwistStamped
    env:
      DEVICE_INDEX: 0

  - id: gnss_poser  #坐标系转化
    custom:
      source: ../../sensing/gnss_poser/build/gnss_poser_core
      inputs:
        DoraNavSatFix: gnss/DoraNavSatFix
      queue_size: 100 
      outputs:
        - DoraNavSatFix 

  - id: gnss_rviz2  #在RVIZ2中显示转换后的轨迹 （E-N-U）
    operator:
      python: ../../sensing/gnss_poser/src/gps_to_ros2.py
      inputs:
        DoraNavSatFix: gnss_poser/DoraNavSatFix
      queue_size: 100 
 
  - id: gnss_ekf  # c/c++节点
    custom:
      source: build/gnss_ekf
      inputs:
              DoraNavSatFix: gnss_poser/DoraNavSatFix
              DoraQuaternionStamped: gnss/DoraQuaternionStamped
      outputs:
            - DoraGnssPose
      queue_size: 100 
      
  - id: ekf_odom_rviz2  #在rviz中显示数据
    operator:
      python: src/ekf_odom_to_ros2.py
      inputs:
          DoraGnssPose: gnss_ekf/DoraGnssPose
      queue_size: 100 
```
