### ISSUE TITLE
Questions regarding the dynamic-node.

### ISSUE THREAD

**Issue by chengzi0103** [dora-rs/dora#618]
**Is your feature request related to a problem? Please describe.**

Regarding the dynamic node, we currently have the following issues:

1. We want the `dynamic-node` to retrieve the output of a specific node, then use `python dynamic.py` to display the received data in the `terminal`.
2. When we have multiple `dataflow` processes and the `dynamic` node names are the same across these processes, why can't we start the same `dynamic` node to send information to multiple `dataflow` processes?

**Comment by haixuanTao** [comment]
2. A node cannot be used for multiple dataflows. You should either rewrite your dataflow to be a single dataflow or try to use multiple dynamic nodes from a single python to make two dataflow collaborate. 

But I would recommend focusing on a single dataflow for now.

1. So is there an issue with printing into the terminal?

**Comment by chengzi0103** [comment]
> 2. A node cannot be used for multiple dataflows. You should either rewrite your dataflow to be a single dataflow or try to use multiple dynamic nodes from a single python to make two dataflow collaborate.
> 
> But I would recommend focusing on a single dataflow for now.
> 
> 1. So is there an issue with printing into the terminal?


Let's discuss the first issue.

When I run the code below, I input a task in the terminal, but the task is not sent to the dataflow, and the dynamic node does not terminate. I'm not sure if there's an issue with my code.

```python
import json
from dora import Node
import pyarrow as pa

node = Node("reasoner_task_input")

event = node.next()
task_data = input('Please enter your task: ')
node.send_output('reasoner_task', pa.array([json.dumps(task_data)]), event["metadata"])

while True:
    event = node.next()
    if event["type"] == "INPUT":
        if event["id"] == "reasoner_log":
            print('-----------  ：', event["value"])
```

**Comment by haixuanTao** [comment]
Could you share `out/dora-daemon.txt` and `out/dora-coordinator.txt`?

**Comment by chengzi0103** [comment]
> Could you share `out/dora-daemon.txt` and `out/dora-coordinator.txt`?


None of the `out/*.txt` files in this process contain any results, and the dataflow itself hasn't been executed.

**Comment by haixuanTao** [comment]
ok could you run:

```bash
dora destroy 
dora up
```

**Comment by chengzi0103** [comment]
> ```shell
> dora destroy 
> ```

1. The result is still that the dora-dataflow wasn't triggered.
2. I'm not sure why the `dynamic` node is receiving the `reasoner_log` message.

Below is the content of my dataflow YAML file:

```yaml
nodes:
  - id: reasoner_task_input
    path: dynamic
    inputs:
      direction: dora/timer/secs/1
      reasoner_log: reasoner_output/reasoner_output
    outputs:
      - reasoner_task
  - id: reasoner_agent
    operator:
      python: ./scripts/reasoner_agent.py
      inputs:
        reasoner_task: reasoner_task_input/reasoner_task
      outputs:
        - reasoner_result
  - id: reasoner_output
    operator:
      python: ./scripts/reasoner_output.py
      inputs:
        reasoner_result: reasoner_agent/reasoner_result
      outputs:
        - reasoner_output
```

---
