### ISSUE TITLE
No Input node does not return `STOP` event

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#627]
**Describe the bug**
Python Node with no input always return `None` on `.next()`  although we would want it to return `STOP` event so that we can gracefully stop it.

```python
import pyarrow as pa
from dora import Node

node = Node()

node.send_output("data", pa.array([1, 2, 3, 4, 5]))

event = node.next()

assert event is not None, "we should expect a STOP event"
assert event["type"] == "STOP", "we should expect a STOP event"
```

```yaml
nodes:
  - id: no_input
    path: no_input.py
    outputs:
      - data

  - id: terminal-print
    build: cargo build -p terminal-print
    path: dynamic
    inputs:
      data: no_input/data

```
