### ISSUE TITLE
Regarding the delivery of events in Dora.

### ISSUE THREAD

**Issue by chengzi0103** [dora-rs/dora#747]
In the add-numbers node, I use a while True loop to continuously retrieve the value of num2. After successfully obtaining the value of num2, I attempt to use the same method to retrieve the value of num1, but I find that num1 is no longer available and has become None. Could you provide a detailed explanation of the event delivery mechanism and its underlying logic?

**Environments**

- System info: mac os 
- Dora version: 0.3.8

**Additional context**

The dataflow configuration is as follows:

```yaml
nodes:
  - id: terminal-input
    build: pip install -e ../../node-hub/terminal-input
    path: dynamic
    outputs:
      - data
    inputs:
      add_numbers_result: add-numbers/add_numbers_result
      multiply_numbers_result: multiply-numbers/multiply_numbers_result
  - id: multiply-numbers
    build: pip install -e ../../agent-hub/multiply-numbers
    path: multiply-numbers
    outputs:
      - multiply_numbers_result
    inputs:
      num1: terminal-input/data
    env:
      IS_DATAFLOW_END: false
  - id: add-numbers
    build: pip install -e ../../agent-hub/add-numbers
    path: add-numbers
    outputs:
      - add_numbers_result
    inputs:
      num1: terminal-input/data
      num2: multiply-numbers/multiply_numbers_result
    env:
      IS_DATAFLOW_END: true
```

1. **Add Logging:**
add-numbers-nodes-logs:

   num2 :  40
   num1 :  None
