### ISSUE TITLE
Local network daemons seem to be connected but are not communicating

### ISSUE THREAD

**Issue by KyloRen1** [dora-rs/dora#751]
**Describe the bug**
Local network daemons seem to be connected but are not communicating, except for the stop command. I am running Dora CLI version 0.3.8 on both machines: one is armv7l, and the other is x86_64. I followed the example in release [v0.3.5](https://github.com/dora-rs/dora/releases/tag/v0.3.5) as provided in my previous [issue](https://github.com/dora-rs/dora/issues/619).

**To Reproduce**
1. On machine A (armv7l) I run: 
```
dora coordinator
dora daemon --machine-id A 
```
3. On machine B (x86_64) I run:
```
dora daemon --machine-id B --coordinator-addr 192.168.1.86 --local-listen-port 53290
dora start dataflow_small.yml --coordinator-addr 192.168.1.86 --coordinator-port 6012
```
5. My `dataflow_small.yml` is supposed to read frames from the armv7l machine and transfer them to machine B. It looks like this:
```
nodes:
  - id: webcam
    _unstable_deploy:
      machine: A
    path: /ABSOLUTE_PATH/dora-main/node-hub/opencv-video-capture/opencv_video_capture/main.py
    inputs:
      tick: dora/timer/millis/16 # try to capture at 60fps
    outputs:
      - image # the captured image
    env:
      PATH: 0 # optional, default is 0
      IMAGE_WIDTH: 640 # optional, default is video capture width
      IMAGE_HEIGHT: 480 # optional, default is video capture height

  - id: plot
    _unstable_deploy:
      machine: B
    path: /ABSOLUTE_PATH/dora-main/node-hub/opencv-plot/opencv_plot/main.py
    inputs:
      image: webcam/image # image: Arrow array of size 1 containing the base image
    env:
      PLOT_WIDTH: 640 # optional, default is image input width
      PLOT_HEIGHT: 480 # optional, default is image input height
```
6. After I run all these commands, there is no error and logs do not produce anything related to camera read and plot. Here is dora-daemon-B logs:
```
2025-01-11T14:56:46.701581Z  INFO dora_daemon::coordinator: Connected to dora-coordinator at 192.168.1.86:53290
2025-01-11T14:56:50.217336Z  INFO run_inner{self.machine_id=B}: dora_daemon::spawn: spawning: "/Users/bogdanivanyuk/Desktop/RaspberryPi-car/dora_computer/venv/bin/python" /Users/bogdanivanyuk/Desktop/RaspberryPi-car/dora-main/node-hub/opencv-plot/opencv_plot/main.py
2025-01-11T14:56:52.263876Z  INFO run_inner{self.machine_id=B}: dora_daemon: node `plot` is ready
2025-01-11T14:56:52.263944Z  INFO run_inner{self.machine_id=B}: dora_daemon::pending: all local nodes are ready (exit before subscribe: []), waiting for remote nodes
``` 

I verified that the camera is working. Additionally, I tried running the armv7l Dora command both within and outside a Python virtual environment with OpenCV installed, but the behavior remained the same.

**Environments (please complete the following information):**
 - System info: armv7l and x86_64
 - Dora version: 0.3.8
