### ISSUE TITLE
Auto-fix dora using pydocstyle from ruff

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#828]
In order to improve code quality,

We can follow up ruff default fix with ruff pydocstyle unsafe fix.

To do this we can run:

```bash
uvx ruff check --select D --unsafe-fixes --fix # D for: https://docs.astral.sh/ruff/rules/#pydocstyle-d
```

In order to make this change last, we should enforce every dora package `pyproject.toml` with:

```toml

[tool.ruff.lint]
extend-select = [
  "D",   # pydocstyle
]
```
