### ISSUE TITLE
errror about operator node in C++

### ISSUE THREAD

**Issue by Jia-Baos** [dora-rs/dora#900]
dataflow.yml file:

```
nodes:
    - id: node-cpp-api
      path: install/bin/node_cpp_api
      inputs:
          tick: dora/timer/millis/300
      outputs:
          - image

    - id: runtime-node-1
      operators:
          - id: operator-plot
            shared-library: install/lib/operator_plot
            inputs:
                image: node-cpp-api/image

```

commands to start dataflow.yml

```
source .venv/bin/activate
dora build dataflow.yml --uv
dora run dataflow.yml --uv
```

[ERROR]
Dataflow failed:

Node `runtime-node-1` failed: exited with code 2 with stderr output:
---------------------------------------------------------------------------------
/home/seer/.local/share/uv/python/cpython-3.11.11-linux-x86_64-gnu/bin/python3.11: can't open file '/home/seer/Project-Rust/dora/examples/cmake-dataflow-camera/runtime': [Errno 2] No such file or directory
---------------------------------------------------------------------------------
